# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb1a0bd5c50cb9eda0981b6df67215c84e2793049f037b98691266adf70611922e05886ce638e1af5441ac7bea9860fc25c5c24372b22bd1a7af3a14b655d213

test:
  secret_key_base: dd349f0053d5632ef327e2274297b0a66ae00020797f80a03f1a68050284ec450591c7f10962c09e2536ffadff5d463b27cc9b7776266dde6859dd1f67a8ef30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
